refactor:Написание кода согласно ТЗ ФП спринта №9
SZFO/java-filmorate pull request #1
Opened 2022-08-02 15:30 UTC by SZFO

2022-08-02 20:06 UTC, FanaticFiz requested changes
Финальный коммент на Я.Практикуме.

2022-08-02 20:06 UTC, FanaticFiz commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ну что же, начнем с "многоуважаемого" `pom` файла ))

Для начала немного причесать: очень не хватает отделения друг от друга (пустыми строками) глобальных частей таких как `parent`, `properties`, `dependencies`

Ну и как минимум не хватает указания кодировки в `properties`
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`

Прочитай про версионирование в формате `0.0.1` ну и не стесняйся, смело проставь версию!

2022-08-02 20:06 UTC, FanaticFiz commented on src/main/resources/application.properties
> +
Я буду топить за то чтобы ты сразу привыкать к написанию файла свойств для приложения в формате `yaml` -> `application.yml`

Соответственно - попрошу тебя этому следовать.
Ну и немного забегая вперед, ну ты же у нас "впереди паровоза" ))
попрошу тебя задать порт...

2022-08-02 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static Map<Integer, Film> films = new HashMap<>();
Какова причина `films` быть `static` ?

2022-08-02 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Некорректно указан id у фильма: " + film);
Мне вот очень интересно, а ты заметил что кидаешь `ValidationException`, но не тот который сам создал!? ))

Потому что у меня вот буквально сегодня был на работе случай, джун сам просидел час не мог понять что не так и потом я минут 10.
Аннотацию `Service` он умудрился воткнуть не спринговую а какую то левую. Называются то одинаково, подвох заметить трудно...

2022-08-02 20:06 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Продолжительность фильма должна быть положительной!");
По результатам валидации мы, как туршные бекендеры )), посылаем запрос куда подальше с формулировкой `BadRequestException`.
Можно было бы создать таковой...

2022-08-03 18:14 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Да кстати, проверяя другую работу заметил.
Проверяем мы валидацию, но ексепшн надо кинуть `BadRequestException` поскольку у нас веб сервис, а клиент прислал неверный запрос.

2022-08-04 16:40 UTC, SZFO commented on src/main/resources/application.properties
> +
Порт задал. Также включил вывод сообщений, чтобы при обработке исключений посредством GlobalHandlerException помимо HTTP-кода получали заданное сообщение.

2022-08-04 16:40 UTC, SZFO commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static Map<Integer, Film> films = new HashMap<>();
Да, static здесь ни к чему, здесь нужен модификатор final

2022-08-04 16:40 UTC, SZFO commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Некорректно указан id у фильма: " + film);
Не заметил, если честно, все тесты программа проходила, даже и не подумал, только после комментария заметил))

2022-08-04 16:41 UTC, SZFO commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Продолжительность фильма должна быть положительной!");
Решил сделать немного по-другому. Создал класс GlobalHandlerException, который в зависимости от исключения возвращает заданный HTTP-код и сообщение. В будущем сообщение можно убрать. 
Мне это вариант обработки исключений показался очень интересным))

Единственное, пока не разобрался, существует ли возможность в javax.validation.constraints или посредством другого пакета сделать валидацию поля  LocalDate releaseDate, чтобы оно было не раньше определённой даты, чтобы например вообще убрать ValidationException, ведь сейчас это исключение нужно только для проверки даты релиза, а для остальных проверок задействованы встроенные MethodArgumentNotValidException и NoSuchElementException

2022-08-04 19:04 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Некорректно указан id у фильма: " + film);
Ну вот и я, просматривая в браузере код именно контроллера, не увидел... а потом заметил что твой ексепшн не используется нигде ))

2022-08-04 19:09 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Продолжительность фильма должна быть положительной!");
Как увидеть какие еще аннотации существуют?
Да очень просто - идешь в импорты и ковыряешься в нужном пакете `import javax.validation.constraints.`
@Past не подойдет?

Ну и всегда можно написать свою...

2022-08-04 19:15 UTC, FanaticFiz approved these changes

2022-08-04 19:15 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/handler/GlobalHandlerException.java
> +public class GlobalHandlerException {
Про это будет дальше в теории ))

2022-08-08 15:25 UTC, merged