feat: Усовершенствование Filmorate согласно ТЗ ФП спринта №12
SZFO/java-filmorate pull request #3
Opened 2022-09-15 20:46 UTC by SZFO

2022-09-16 20:03 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-09-16 20:03 UTC, FanaticFiz commented on pom.xml
> +			<version>2.7.3</version>
Привет...
Знаешь как я напрягся когда увидел это: `+17,937 −434`
17к новых строк кода, ааа!

А оказалось что ты не добавил в гит-игнор папку с базой данных: `db` и это всё из `trace.db`.

Убери файлы и добавь исключение в игнор.

2022-09-16 20:03 UTC, FanaticFiz commented on pom.xml
> +			<version>2.7.3</version>
В pom тоже можно пользоваться переменными, есть системные переменные и можешь объявлять свои в `properties`.
И вот первый кандидат это версия спринга `2.7.3`

2022-09-16 20:03 UTC, FanaticFiz commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jdbc</artifactId>
Кстати старайся поддерживать определённый порядок.
Держи все зависимости спринга например вместе, один за одним без разделителей. 
Потом разделитель - пустая строка. И другие зависимости.

У меня в проектах например так:
- тяжелые зависимости, фреймворки начиная со спринга.
- просто утилитарные либы
- наши внутренние либы/межсервисные контракты

2022-09-16 20:03 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +(
Старайся тут тоже все выравнивать, гораздо легче воспринимать на глаз

```
CREATE TABLE IF NOT EXISTS users
(
    id       INT auto_increment PRIMARY KEY,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL UNIQUE,
    email    VARCHAR(255) NOT NULL UNIQUE,
    birthday DATE         NOT NULL
);
```

2022-09-16 20:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        return filmStorage.findAll();
У тебя при выборке фильмов по одному жанры есть, а при выборке всех фильмов жанров нет...

Это ты так избежал проблем с их доставанием? ))
Ну потому что у всех тут есть некоторые сложности...

2022-09-16 20:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends ResponseStatusException {
А почему ты решил один из эксепшенов унаследовать от другого родителя?

2022-09-16 20:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(message = "Электронная почта не может быть пустой и должна содержать символ @!")
Делай пожалуйста отступы между полями...

2022-09-16 20:03 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorageDao.java
> +    Optional<User> updateUser(User user);
Смотри, название методов...
Ну во первых: `не консистентно`! один метод просто `create`, а рядом не `update`, а `updateUser`. Почему тогда не `createUser`.
Просто будь последователен. Даже если и не прав.

Во вторых: методы, которые ты называешь, не висят в воздухе... ты в контексте `UserStorageDao` т.е. я топлю всегда за то что НЕ нужно добавлять `user`, просто: `update`, `delete`

В коде если мы посмотрим: `userService.updateUser(user);` 
Ничего не потеряется: `userService.update(user);`

2022-09-18 12:13 UTC, SZFO commented on pom.xml
> +			<version>2.7.3</version>
Упустил этот момент. Думал, что автоматом будет игнорироваться.

2022-09-18 12:14 UTC, SZFO commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        return filmStorage.findAll();
Вот уж неожиданно, тесты в Postman проходили, вот я и подумал, что всё ОК здесь, а тут у меня такая недоработка оказалась))

2022-09-18 12:14 UTC, SZFO commented on src/main/java/ru/yandex/practicum/filmorate/exception/NotFoundException.java
> +public class NotFoundException extends ResponseStatusException {
Да, тут переделал, как и было раньше, наследование от RuntimeException. Просто, когда проект делал, запутался, что у меня уже есть класс ErrorHandler, который выдает нужный ResponseStatus

2022-09-18 12:15 UTC, SZFO commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(message = "Электронная почта не может быть пустой и должна содержать символ @!")
Не раз замечал, что IDEA у меня по умолчанию (Ctrl + Alt + L) не отделяет поля пустой строкой друг от друга. Методы, к примеру, да, а поля нет. Ранее всё вручную делал, а тут пропустил и после замечания в настройках IDEA всё-таки нашёл и настроил добавление пустой строки между полями при нажатии Ctrl + Alt + L.

2022-09-18 18:28 UTC, FanaticFiz approved these changes

2022-09-18 18:28 UTC, FanaticFiz commented on .gitignore
> +/db/
ну получается ты добавил это в секцию `### VS Code ###`

2022-09-18 18:28 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +        return films.stream()
Советую еще найти опцию выравнивания и написать в одну строку.

```
return filmStorage.getAll().stream()
                  .peek(film -> film.setGenres(genreStorage.load(film)))
                  .collect(Collectors.toList());
```

2022-09-20 18:34 UTC, merged